"""empty message

Revision ID: 27818c8d1398
Revises: 
Create Date: 2019-06-10 22:49:39.062869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27818c8d1398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('name', 'url', name='name_url_unique_constraint')
    )
    op.create_table('aneks',
    sa.Column('anek_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('anek_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aneks')
    op.drop_table('sources')
    # ### end Alembic commands ###
